AIOS Modularization Pt.1: Functional Components
agiresearch/AIOS pull request #199
Opened 2024-08-05 22:58 UTC by BRama10

Thank you for your contribution to AIOS!
Before submitting the pull request, please ensure **the PR meets the following criteria**! This helps improve the efficiency of the review process.

### Code Quality
Before submitting your PR, you need to follow the steps below to maintain code quality.
- Use `pip install -r requirements-dev.txt` to install the extra dependencies in requirements-dev.txt for the following checks.
- Use `pre-commit install` to install pre-commit locally before you commit messages. The pre-commit can help correct the style that are added or modified.

### PR title and classification
Only specific types of PRs will be reviewed. The PR title is prefixed appropriately (i.e., "prefix: description") to indicate the type of change. Please use one of the prefixs as below:
- `feat` Add new features
- `fix`  Fix bugs
- `docs` Modify documents like README, CONTRIBUTE
- `style` Modify code format like space and comma without changing code logic
- `refactor` Refactor code structure without adding new features or fixing new bugs
- `perf` Improve performance or user experience
- `test` Test features, including unit test and integration test
- `chore` Change the build procedure or add dependencies
- `revert` Revert to the previous version

### PR messages
- **Description:** a description of the change
- **Issue:** the issue # it fixes, if applicable
- **Dependencies:** any dependencies required for this change

### For the Reviews
- After the PR is submitted, the PR will be assigned to a reviewer. Every reviewer will pick up the PRs based on their expertise and availability.
- If no one reviews your PR within a few days, please @-mention one of [dongyuanjushi](https://github.com/dongyuanjushi/), [evison](https://github.com/evison), [BRama10](https://github.com/BRama10), [JHSUYU](https://github.com/JHSUYU), [WujiangXu](https://github.com/WujiangXu), [MingyuJ666](https://github.com/MingyuJ666), [xizhu1022](https://github.com/xizhu1022).

2024-08-06 02:53 UTC, dongyuanjushi requested changes
Thank you for the big changes. Could you do the following things before the review?
1) Pip install requirements-dev.txt in your local environment to regulate files as it currently can not pass the ruff check.
2) Add more details in the PR message to facilitate the track of changes.
3) Rm log files (log.json, log.txt)

2024-08-06 06:00 UTC, BRama10 commented
2. and 3. done

1. may need to be bypassed since some code structures are being blocked by ruff altogether?

2024-08-06 17:39 UTC, dongyuanjushi commented
> 2. and 3. done
> 
> \1. may need to be bypassed since some code structures are being blocked by ruff altogether?

Some rules can be modified if that is too stringent. But the ruff check is still necessary to pass.

2024-08-07 14:35 UTC, dongyuanjushi approved these changes

2024-08-07 14:35 UTC, merged