[feat] Transcription Agent example!
agiresearch/AIOS pull request #213
Opened 2024-08-20 22:17 UTC by om-raheja

Transcription Agent
Description: Can listen to the microphone and execute tasks with the output. On request of @mannanshukla 
Dependencies: RealtimeSTT

Pretty self explanatory. Tested and works, if any issues come up please don't hesitate to @ me.

2024-08-21 02:04 UTC, dongyuanjushi commented on pyopenagi/tools/transcriber/transcriber.py
The tool class for the transcriber is shown as CurrencyConverter, which is incorrect

2024-08-21 02:07 UTC, dongyuanjushi requested changes
Could you make the changes according to the above comments?

2024-08-21 14:20 UTC, om-raheja commented
Hey Kai, I renamed the class to Transcriber before submitting the PR and I can't find where it says CurrencyConverter, neither locally nor in my diff nor on GitHub. I made some other needed adjustments to ensure code quality this morning, and I double checked all my class names. If there is anything else, please let me know. Sorry for the inconvenience.

2024-08-21 15:29 UTC, mannanshukla commented
The class you used is called CurrencyConverter, just rename it.Sent from my iPhoneOn Aug 21, 2024, at 10:20 AM, om-raheja ***@***.***> wrote:﻿
Hey Kai, I renamed the class to Transcriber before submitting the PR and I can't find where it says CurrencyConverter, neither locally nor in my diff nor on GitHub. I made some other needed adjustments to ensure code quality this morning, and I double checked all my class names. If there is anything else, please let me know. Sorry for the inconvenience.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-08-21 15:42 UTC, BRama10 requested changes
In `interact.py`, have `stderr` still print to the console (or at worst, to a logfile), so that in the case of an error due to dependencies (which has happened many times before).

On second thought, also have `stdout` go to a logfile as well.

In `server.py` can you set up default arguments, and only in case of an error (such as the one you were getting), do we fallback onto parser args (since it is a hassle to pass args).

2024-08-21 17:05 UTC, om-raheja commented
Balaji, will do the changes for interact.py. The way the parser is setup is that if no args are passed, the defaults you had before are automatically applied. Check the arg parser code.I can't find where the CurrencyConverter class is. Like I said before, its not in my diffs, my local files, or in GitHub. If you can show me where it is, I'll gladly change it.On Aug 21, 2024, at 11:43, BRama10 ***@***.***> wrote:﻿
@BRama10 requested changes on this pull request.

In interact.py, have stderr still print to the console (or at worst, to a logfile), so that in the case of an error due to dependencies (which has happened many times before).
On second thought, also have stdout go to a logfile as well.
In server.py can you set up default arguments, and only in case of an error (such as the one you were getting), do we fallback onto parser args (since it is a hassle to pass args).

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-21 19:51 UTC, BRama10 commented
> Balaji, will do the changes for interact.py. The way the parser is setup is that if no args are passed, the defaults you had before are automatically applied. Check the arg parser code.I can't find where the CurrencyConverter class is. Like I said before, its not in my diffs, my local files, or in GitHub. If you can show me where it is, I'll gladly change it.On Aug 21, 2024, at 11:43, BRama10 ***@***.***> wrote:﻿ @BRama10 requested changes on this pull request. In interact.py, have stderr still print to the console (or at worst, to a logfile), so that in the case of an error due to dependencies (which has happened many times before). On second thought, also have stdout go to a logfile as well. In server.py can you set up default arguments, and only in case of an error (such as the one you were getting), do we fallback onto parser args (since it is a hassle to pass args). —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I don't think CurrencyConverter ever was a problem (for some reason, your 2nd commit has CurrencyConverter, but your 3rd commit renames it to Transcriptor, so I assume you committed halfway through refactoring the class), so you can safely ignore that!

2024-08-22 13:44 UTC, dongyuanjushi approved these changes

2024-08-23 15:18 UTC, BRama10 approved these changes

2024-08-23 15:18 UTC, merged